version: '2'
pipelines:
  - name: sample-app-aws-ecs-fargate:0.1.1
    description: build sample application
    env:
      static:
        - AWS_REGION=us-west-1
        - DOCKER_REGISTRY=ghcr.io
        - ORG=workflows-sh
        - REF=CUSTOM
        - REPO=sample-expressjs-aws-ecs-fargate
        - STACK_TYPE=aws-ecs-fargate
      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_ACCOUNT_NUMBER
        - AWS_SECRET_ACCESS_KEY
        - GITHUB_TOKEN
    events:
      - 'github:workflows-sh/sample-expressjs-aws-ecs-fargate:pull_request.opened'
      - 'github:workflows-sh/sample-expressjs-aws-ecs-fargate:pull_request.reopened'
    jobs:
      - name: build-sample-app-aws-ecs-fargate
        description: Build sample app image
        packages:
          - git
          - unzip
          - python
          - wget
          - tar
        steps:
          - set +u
          - curl https://s3.amazonaws.com/aws-cli/awscli-bundle-1.18.200.zip -o awscli-bundle.zip
          - unzip awscli-bundle.zip && ./awscli-bundle/install -b ~/bin/aws
          - export PATH=~/bin:$PATH
          - aws --version
          - git clone https://oauth2:$GITHUB_TOKEN@github.com/$ORG/$REPO
          - cd $REPO && ls -asl #only remote
          - RAW_BRANCH_LIST=`git branch -r --sort=-committerdate | grep -v HEAD | head -n 20 | sed 's:.*/::' | awk '{print}' ORS="' '"` #only remote
          - echo "ux prompt list '$RAW_BRANCH_LIST$REF' --message='Select the repository branch to build' --name='reference'" >> /tmp/ux.sh && chmod 755 /tmp/ux.sh #only remote
          - if [ "${REF}" = "CUSTOM"  ]; then REF=`/tmp/ux.sh`; fi #only remote
          - if [ "${REF}" = "CUSTOM" ]; then REF=`ux prompt input --message='Enter the repository branch to build' --name='reference'`; fi && echo "Going to checkout $REF" #only remote
          - git fetch && git checkout $REF #only remote
          - ls -asl #only locally
          - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO-$STACK_TYPE
          - docker build -t $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO-$STACK_TYPE:$REF .
          - docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO-$STACK_TYPE:$REF
